name: test docker

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  main:
    runs-on: macos-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0

      - run: |
          brew install --cask docker
          docker run hello-world
